if(!localStorage.auth)location.href='login.html';
var t=localStorage.theme||'dark',tb=document.getElementById('themeBtn');
if(t=='light'){document.body.classList.add('light');tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>';}else{tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';}
function setT(m){if(m=='light'){document.body.classList.add('light');tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>';localStorage.theme='light';}else{document.body.classList.remove('light');tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';localStorage.theme='dark';}}
setT(t);
tb.onclick=function(){setT(localStorage.theme=='dark'?'light':'dark')};
document.getElementById('notifBtn').onclick=function(){alert('Report ready\nDeepfake: 92.3%')};
document.getElementById('profileBtn').onclick=showProfile;
function showProfile(){var u=localStorage.user||'User',e=localStorage.email||'user@agency.gov',l=localStorage.lab||'Lab';var m=document.createElement('div');m.className='modal';m.innerHTML='<div class="modal-content"><div class="modal-header"><h3>Profile</h3><button class="close-btn" onclick="this.closest(\'.modal\').remove()">×</button></div><div class="modal-body"><div class="form-group"><label>Name</label><input id="editName" value="'+u+'"></div><div class="form-group"><label>Email</label><input id="editEmail" value="'+e+'"></div><div class="form-group"><label>Lab</label><input id="editLab" value="'+l+'"></div></div><div class="modal-footer"><button class="btn-save" onclick="saveProfile()">Save</button><button class="btn-logout" onclick="logout()">Logout</button></div></div>';document.body.appendChild(m);}
function saveProfile(){var n=document.getElementById('editName').value,e=document.getElementById('editEmail').value,l=document.getElementById('editLab').value;if(!n||!e||!l){alert('Fill all');return;}localStorage.user=n;localStorage.email=e;localStorage.lab=l;document.querySelector('.modal').remove();alert('Updated');}
function logout(){var m=document.querySelector('.modal');if(m)m.remove();localStorage.clear();location.href='login.html'}
window.saveProfile=saveProfile;window.logout=logout;
var c=document.getElementById('heatmap'),ctx=c.getContext('2d');
function resize(){c.width=c.offsetWidth;c.height=c.offsetHeight;draw()}
function draw(){var w=c.width,h=c.height;var bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#0f1419');bg.addColorStop(1,'#1a1a1a');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);var lh=3,gap=2,num=Math.floor(h/(lh+gap));for(var i=0;i<num;i++){var y=i*(lh+gap),intensity=Math.random(),color;if(intensity>0.95){color='rgba(255,255,200,'+(0.8+Math.random()*0.2)+')';}else if(intensity>0.7){color='rgba(34,197,94,'+(0.3+Math.random()*0.3)+')';}else if(intensity>0.4){color='rgba(22,163,74,'+(0.2+Math.random()*0.2)+')';}else{color='rgba(20,83,45,'+(0.1+Math.random()*0.1)+')';}ctx.fillStyle=color;var lw=w*(0.8+Math.random()*0.2),xo=(w-lw)/2;ctx.fillRect(xo,y,lw,lh);}var cy=h/2,ar=h*0.2;for(var i=0;i<50;i++){var x=Math.random()*w,y=cy-ar/2+Math.random()*ar,size=2+Math.random()*4;if(Math.random()>0.7){ctx.fillStyle='rgba(255,255,255,'+(0.6+Math.random()*0.4)+')';ctx.fillRect(x,y,size,size);}}}
window.onresize=resize;resize();
function copy(){var h=document.getElementById('hash').textContent;navigator.clipboard.writeText(h).then(function(){var b=document.querySelector('.copy');b.textContent='✓';setTimeout(function(){b.textContent='📋'},2000)})}
document.querySelector('.primary').onclick=function(){var w=window.open('','_blank');w.document.write('<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Forensic Report</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;padding:40px;color:#000;background:#fff}.header{text-align:center;margin-bottom:30px;border-bottom:3px solid #3B82F6;padding-bottom:20px}.header h1{font-size:28px;color:#0f172a;margin-bottom:10px}.section{margin-bottom:25px}.section h2{font-size:18px;color:#0f172a;margin-bottom:15px;border-left:4px solid #3B82F6;padding-left:10px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.info-item{padding:15px;background:#f8fafc;border-radius:8px}.alert-box{background:#fef2f2;border:2px solid #ef4444;border-radius:8px;padding:20px;margin:20px 0}.badge{display:inline-block;padding:6px 12px;border-radius:6px;font-size:12px;font-weight:700;margin-right:10px}.badge-red{background:#fee2e2;color:#dc2626}.footer{margin-top:40px;padding-top:20px;border-top:2px solid #e2e8f0;text-align:center;font-size:12px}</style></head><body><div class="header"><h1>FORENSIC ANALYSIS REPORT</h1><p>Deepfake Detection System</p></div><div class="section"><h2>Case Information</h2><div class="info-grid"><div class="info-item"><strong>CASE ID:</strong> CHAK36-CS-05</div><div class="info-item"><strong>ANALYST:</strong> '+localStorage.user+'</div><div class="info-item"><strong>DATE:</strong> '+new Date().toLocaleDateString()+'</div><div class="info-item"><strong>STATUS:</strong> Complete</div></div></div><div class="alert-box"><strong>⚠️ MANIPULATION DETECTED</strong><p>Deepfake Score: 92.3% - High confidence manipulation detected</p></div><div class="section"><h2>Classification</h2><p><span class="badge badge-red">MANIPULATED</span></p></div><div class="section"><h2>Technical Details</h2><p>Encryption: AES-256 Bit Secure</p><p>Hash: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6</p></div><div class="footer"><p>© 2024 Deepfake Detection System</p><p>Report ID: RPT-'+Date.now()+'</p></div></body></html>');w.document.close();setTimeout(function(){w.print()},250)};
