if(!localStorage.auth)location.href='login.html';
var t=localStorage.theme||'dark',tb=document.getElementById('themeBtn'),ts=document.getElementById('themeSelect');
function setT(m){if(m=='light'){document.body.classList.add('light');tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>';localStorage.theme='light';ts.value='light';}else{document.body.classList.remove('light');tb.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';localStorage.theme='dark';ts.value='dark';}}
setT(t);
tb.onclick=function(){setT(localStorage.theme=='dark'?'light':'dark')};
ts.onchange=function(){setT(this.value)};
function loadProfile(){var u=localStorage.user||'Agent Smith',e=localStorage.email||'agent@agency.gov',l=localStorage.lab||'Lab';document.getElementById('displayUser').textContent=u;document.getElementById('displayEmail').textContent=e;document.getElementById('displayLab').textContent=l;}
loadProfile();
var tg=document.querySelectorAll('.toggle input'),sl=document.querySelectorAll('.select-input');
function loadSettings(){tg[0].checked=localStorage['2fa']=='true';sl[1].value=localStorage.sessionTimeout||'30 minutes';tg[1].checked=localStorage.notifAnalysis!='false';tg[2].checked=localStorage.notifSystem!='false';tg[3].checked=localStorage.autoDelete=='true';}
loadSettings();
tg[0].onchange=function(){localStorage['2fa']=this.checked;alert(this.checked?'2FA enabled':'2FA disabled')};
sl[1].onchange=function(){localStorage.sessionTimeout=this.value;alert('Timeout: '+this.value)};
tg[1].onchange=function(){localStorage.notifAnalysis=this.checked;alert(this.checked?'Analysis notif on':'Analysis notif off')};
tg[2].onchange=function(){localStorage.notifSystem=this.checked;alert(this.checked?'System notif on':'System notif off')};
tg[3].onchange=function(){localStorage.autoDelete=this.checked;alert(this.checked?'Auto-delete on':'Auto-delete off')};
document.getElementById('notifBtn').onclick=function(){var na=localStorage.notifAnalysis!='false',ns=localStorage.notifSystem!='false',m=[];if(na){m.push('• Analysis complete');m.push('• Evidence uploaded');}if(ns)m.push('• System update');alert(m.length?'Notifications:\n\n'+m.join('\n'):'No notifications')};
document.getElementById('profileBtn').onclick=showProfile;
function showProfile(){var u=localStorage.user||'User',e=localStorage.email||'user@agency.gov',l=localStorage.lab||'Lab';var m=document.createElement('div');m.className='modal';m.innerHTML='<div class="modal-content"><div class="modal-header"><h3>Profile</h3><button class="close-btn" onclick="this.closest(\'.modal\').remove()">×</button></div><div class="modal-body"><div class="form-group"><label>Name</label><input id="editName" value="'+u+'"></div><div class="form-group"><label>Email</label><input id="editEmail" value="'+e+'"></div><div class="form-group"><label>Lab</label><input id="editLab" value="'+l+'"></div></div><div class="modal-footer"><button class="btn-save" onclick="saveProfile()">Save</button><button class="btn-logout" onclick="logout()">Logout</button></div></div>';document.body.appendChild(m);}
function saveProfile(){var n=document.getElementById('editName').value,e=document.getElementById('editEmail').value,l=document.getElementById('editLab').value;if(!n||!e||!l){alert('Fill all');return;}localStorage.user=n;localStorage.email=e;localStorage.lab=l;loadProfile();document.querySelector('.modal').remove();alert('Updated');}
function logout(){var m=document.querySelector('.modal');if(m)m.remove();localStorage.clear();location.href='login.html'}
function clearData(){if(confirm('Clear all data?')){var a=localStorage.auth,u=localStorage.user,e=localStorage.email,l=localStorage.lab,t=localStorage.theme,f=localStorage['2fa'],st=localStorage.sessionTimeout,na=localStorage.notifAnalysis,ns=localStorage.notifSystem,ad=localStorage.autoDelete;localStorage.clear();sessionStorage.clear();localStorage.auth=a;localStorage.user=u;localStorage.email=e;localStorage.lab=l;localStorage.theme=t;if(f)localStorage['2fa']=f;if(st)localStorage.sessionTimeout=st;if(na)localStorage.notifAnalysis=na;if(ns)localStorage.notifSystem=ns;if(ad)localStorage.autoDelete=ad;alert('Data cleared');}}
function deleteAccount(){if(confirm('Delete account? Cannot undo!')){if(confirm('Final warning!')){localStorage.clear();sessionStorage.clear();alert('Account deleted');location.href='login.html'}}}
window.saveProfile=saveProfile;window.logout=logout;window.clearData=clearData;window.deleteAccount=deleteAccount;
